# Generated by Django 5.1.5 on 2025-01-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='priority',
            field=models.CharField(choices=[('M', 'Medium'), ('H', 'High'), ('L', 'Low')], default='L', max_length=1),
        ),
    ]
