# Generated by Django 5.1.5 on 2025-01-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_employee_alter_taskdetail_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(to='tasks.employee'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'Medium')], default='L', max_length=1),
        ),
    ]
